# Wisconsin Breast Cancer Data
## Tumor Prediction Using KNN

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# load data
wdbc = pd.read_csv("Data/wdbc.data", header=None)
wdbc.sample(5)

0  1       2      3       4      5        6        7        8   \
344  89864002  B  11.710  15.45   75.03  420.3  0.11500  0.07281  0.04006   
175    872113  B   8.671  14.45   54.42  227.2  0.09138  0.04276  0.00000   
264    889719  M  17.190  22.07  111.60  928.3  0.09726  0.08995  0.09061   
105    863030  M  13.110  15.56   87.21  530.2  0.13980  0.17650  0.20710   
442  90944601  B  13.780  15.79   88.37  585.9  0.08817  0.06718  0.01055   

           9    ...         22     23      24      25      26       27  \
344  0.032500   ...     13.060  18.16   84.16   516.4  0.1460  0.11150   
175  0.000000   ...      9.262  17.04   58.36   259.2  0.1162  0.07057   
264  0.065270   ...     21.580  29.33  140.50  1436.0  0.1558  0.25670   
105  0.096010   ...     16.310  22.40  106.40   827.2  0.1862  0.40990   
442  0.009937   ...     15.270  17.50   97.90   706.6  0.1072  0.10710   

          28       29      30       31  
344  0.10870  0.07864  0.2765  0.07806  
175  0.00000  0.00000  0.2592  0.07848  
264  0.38890  0.19840  0.3216  0.07570  
105  0.63760  0.19860  0.3147  0.14050  
442  0.03517  0.03312  0.1859  0.06810  

[5 rows x 32 columns]

In [3]:
# split data into dependant and independant variables
X=wdbc.iloc[:,2:32].values
y=wdbc.iloc[:,1:2].values
[X.shape, y.shape]

[(569, 30), (569, 1)]

In [4]:
# encode tumor type data
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y[0:5]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 1, 1, 1, 1], dtype=int64)

In [5]:
# test and train set split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)
[X_test.shape, y_test.shape]

[(114, 30), (114,)]

In [6]:
# standard scaling based on mean and variance
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)
X_train[0:2,:]
# option2: use normalize to scale to [0,1]

array([[-1.15036482, -0.39064196, -1.12855021, -0.95876358,  0.3109837 ,
        -0.5959945 , -0.80259612, -0.80249002,  0.29453906,  0.0942515 ,
        -0.4950523 ,  1.48720153, -0.51448782, -0.49154005,  0.28149837,
        -0.60451206, -0.46900701, -0.61170002,  0.05798237, -0.35763702,
        -1.0431756 ,  0.21353282, -1.0360446 , -0.84880771,  0.34249851,
        -0.73009743, -0.81232053, -0.75798367, -0.01614761, -0.38503402],
       [-0.93798972,  0.68051405, -0.94820146, -0.82152548, -0.60963604,
        -0.90986721, -0.66066905, -0.89871612,  0.75493453, -0.42547082,
        -0.33381757,  0.75941203, -0.28751805, -0.42127695, -0.1620797 ,
        -0.20486693, -0.05029632, -0.20309076, -0.25469005, -0.39139463,
        -0.71565415,  1.06684183, -0.68992205, -0.66869703, -0.09553745,
        -0.53786647, -0.37504806, -0.60687023,  0.09669004, -0.38615797]])

In [7]:
# train the KNN classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [8]:
# predicting the tumor type on the test set
y_pred = knn.predict(X_test)

In [9]:
# making a confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[67,  0],
       [ 4, 43]], dtype=int64)